import { KeyLegend } from './legend'
import { Controller } from './controller'

/**
 * Map of key identifiers or key patterns to key functionality.
 *
 * Key identifiers symbols are expressed as `q`, `C-c`, `S-return`, `escape`
 * or `return`.
 *
 * Key patterns are regular expressions enclosed in slashes, e.g. `/[a-z]/`.
 */
export type KeyMap = Record<string, KeyMapping>

export type KeyIdentifier = string | string[]

export type KeyMapping = {
  propagate?: boolean
  handler: Function
} & KeyLegend

/**
 * Resolves the handler function for the keypress described by `ch` and `key`
 * as defined in `keyMap`
 *
 * @param keyMap The KeyMap to resolve the handler from
 * @param ch The character string, if any, generated by the keypress
 * @param key The key object generated by the keypress
 *
 * @return The handler function if a match was found, otherwise `undefined`
 */
export const keyHandler = (
  keyMap: KeyMap,
  ch: string | undefined,
  key: any
) => {
  const reKeys = Object.keys(keyMap).filter(
    (pt) => pt.startsWith('/') && pt.endsWith('/')
  )

  if (ch !== undefined) {
    for (const pattern of reKeys) {
      if (ch.match(new RegExp(pattern.substring(1, pattern.length - 1)))) {
        return keyMap[pattern].handler
      }
    }
  }

  return keyMap[key.full]?.handler
}

/**
 * Get the effective KeyMap of a component, including entries that
 * would be caught by event bubbling.
 *
 * @param controller The controller to get the effective keymap for
 * @returns The effective keymap
 */
export const getEffectiveKeyMap = (controller: Controller) => {
  let keyMap: KeyMap = {}

  let next: Controller | undefined = controller

  while (next) {
    keyMap = { ...next.keyMap, ...keyMap }
    next = next.parent
  }

  return keyMap
}
